//! #303: bound what Duckle itself accumulates.
//!
//! A long-running server grows run history, run-scoped logs, receipts and a
//! content-addressed stage cache, and none of it is bounded by anything the
//! pipelines do. This is housekeeping for data Duckle owns - not object-storage
//! lifecycle, not DuckLake snapshot expiry.
//!
//! ## What is prunable, and what is never touched
//!
//! Prunable, because all of it is derivable or historical:
//!
//! | category | what it is | why losing it is survivable |
//! |---|---|---|
//! | `cache` | content-addressed stage outputs | regenerated by re-running the stage |
//! | `logs` | per-run NDJSON | history of what happened, not state |
//! | `runs` | per-pipeline run history | already capped at 50 per pipeline |
//! | `receipts` | per-run receipts for `retry` | already capped at 200 |
//!
//! **`.duckle/` is never touched, at all.** It holds the workspace encryption
//! key, saved watermarks and resume positions, known host keys, alert state and
//! the accepted XSD contracts. Deleting a watermark does not lose history, it
//! silently re-ingests or skips data. That is not a retention decision, so this
//! module refuses to make it: `apply` re-checks every path against the prunable
//! roots, so even a caller that hands it something else cannot get it deleted.
//!
//! ## One plan, two uses
//!
//! `--dry-run` and a real prune call the SAME `plan()` and differ only in
//! whether `apply()` runs. A dry run that computed its list separately would
//! eventually disagree with the prune, which is the one thing a dry run must
//! never do.

use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

/// Directories this module may ever delete inside. Anything not under one of
/// these is refused, whatever a caller asks for.
const PRUNABLE_ROOTS: &[&str] = &["cache", "logs", "runs"];

#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CategoryUse {
    pub category: String,
    pub files: u64,
    pub bytes: u64,
    /// Age of the oldest file, in whole days. `None` when the category is empty.
    pub oldest_days: Option<u64>,
}

#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Removal {
    pub path: String,
    pub category: String,
    pub bytes: u64,
    pub reason: String,
}

#[derive(Debug, Clone, Default)]
pub struct Policy {
    /// Delete cached stage outputs not touched for this many days.
    pub cache_days: Option<u64>,
    /// Delete run logs older than this.
    pub logs_days: Option<u64>,
    /// Keep this many receipts, newest first.
    pub receipts_keep: Option<usize>,
}

fn file_age_days(p: &Path, now: SystemTime) -> Option<u64> {
    let m = std::fs::metadata(p).ok()?;
    let modified = m.modified().ok()?;
    now.duration_since(modified).ok().map(|d| d.as_secs() / 86_400)
}

fn walk(dir: &Path, out: &mut Vec<(PathBuf, u64)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        match e.file_type() {
            Ok(t) if t.is_dir() => walk(&p, out),
            Ok(t) if t.is_file() => {
                let bytes = e.metadata().map(|m| m.len()).unwrap_or(0);
                out.push((p, bytes));
            }
            _ => {}
        }
    }
}

/// What each category currently costs.
pub fn survey(workspace: &Path) -> Vec<CategoryUse> {
    let now = SystemTime::now();
    let mut out = Vec::new();
    for (name, dir) in [
        ("cache", workspace.join("cache")),
        ("logs", workspace.join("logs")),
        ("runs", workspace.join("runs")),
        ("receipts", workspace.join("runs").join("receipts")),
    ] {
        let mut files = Vec::new();
        walk(&dir, &mut files);
        // `runs` contains `receipts`; reported separately, so do not count twice.
        if name == "runs" {
            let receipts = workspace.join("runs").join("receipts");
            files.retain(|(p, _)| !p.starts_with(&receipts));
        }
        let bytes = files.iter().map(|(_, b)| b).sum();
        let oldest = files.iter().filter_map(|(p, _)| file_age_days(p, now)).max();
        out.push(CategoryUse {
            category: name.to_string(),
            files: files.len() as u64,
            bytes,
            oldest_days: oldest,
        });
    }
    out
}

/// Is this path inside something we are allowed to delete from?
///
/// Belt and braces: `plan` only ever produces paths under these roots, and
/// `apply` checks again. The check exists so that a future caller building a
/// plan by hand cannot reach `.duckle/`.
fn prunable(workspace: &Path, path: &Path) -> bool {
    PRUNABLE_ROOTS
        .iter()
        .any(|r| path.starts_with(workspace.join(r)))
        && !path.starts_with(workspace.join(".duckle"))
}

/// What a prune WOULD remove. The same function backs `--dry-run` and the real
/// thing, so the two cannot disagree.
pub fn plan(workspace: &Path, policy: &Policy) -> Vec<Removal> {
    let now = SystemTime::now();
    let mut out = Vec::new();

    if let Some(days) = policy.cache_days {
        let mut files = Vec::new();
        walk(&workspace.join("cache"), &mut files);
        for (p, bytes) in files {
            if file_age_days(&p, now).is_some_and(|a| a > days) {
                out.push(Removal {
                    path: p.display().to_string(),
                    category: "cache".into(),
                    bytes,
                    reason: format!("not used for more than {days} days"),
                });
            }
        }
    }

    if let Some(days) = policy.logs_days {
        let mut files = Vec::new();
        walk(&workspace.join("logs"), &mut files);
        for (p, bytes) in files {
            // The audit log is evidence, not housekeeping. A retention policy
            // that quietly deleted it would remove the record of its own
            // deletions, which is the one file that must outlive a prune.
            if p.file_name().is_some_and(|f| f == "audit.ndjson") {
                continue;
            }
            if file_age_days(&p, now).is_some_and(|a| a > days) {
                out.push(Removal {
                    path: p.display().to_string(),
                    category: "logs".into(),
                    bytes,
                    reason: format!("older than {days} days"),
                });
            }
        }
    }

    if let Some(keep) = policy.receipts_keep {
        let dir = workspace.join("runs").join("receipts");
        let mut files = Vec::new();
        walk(&dir, &mut files);
        let mut dated: Vec<(SystemTime, PathBuf, u64)> = files
            .into_iter()
            .filter_map(|(p, b)| {
                let m = std::fs::metadata(&p).ok()?.modified().ok()?;
                Some((m, p, b))
            })
            .collect();
        dated.sort_by(|a, b| b.0.cmp(&a.0)); // newest first
        for (_, p, bytes) in dated.into_iter().skip(keep) {
            out.push(Removal {
                path: p.display().to_string(),
                category: "receipts".into(),
                bytes,
                reason: format!("beyond the newest {keep}"),
            });
        }
    }

    out.retain(|r| prunable(workspace, Path::new(&r.path)));
    out
}

/// Carry out a plan. Returns what was actually removed, which can be fewer than
/// planned if something disappeared in between - that is not an error.
pub fn apply(workspace: &Path, plan: &[Removal]) -> (usize, u64) {
    let (mut n, mut bytes) = (0usize, 0u64);
    for r in plan {
        let p = PathBuf::from(&r.path);
        // Checked AGAIN here, not only in plan(). This is the line that makes
        // "never touches .duckle" a property of the code rather than of the
        // caller's good behaviour.
        if !prunable(workspace, &p) {
            continue;
        }
        if std::fs::remove_file(&p).is_ok() {
            n += 1;
            bytes += r.bytes;
        }
    }
    if n > 0 {
        // AC5: a prune is auditable. Recorded in the same log every other
        // administrative action goes to.
        duckle_duckdb_engine::audit::note(
            workspace,
            "retention.prune",
            "workspace",
            Some(format!("removed {n} files, {bytes} bytes")),
        );
    }
    (n, bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn touch(p: &Path, bytes: usize, age_days: u64) {
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        let mut f = std::fs::File::create(p).unwrap();
        f.write_all(&vec![b'x'; bytes]).unwrap();
        drop(f);
        let when = SystemTime::now() - Duration::from_secs(age_days * 86_400 + 60);
        let _ = filetime::set_file_mtime(p, filetime::FileTime::from_system_time(when));
    }

    #[test]
    fn survey_reports_each_category_without_double_counting_receipts() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();
        touch(&ws.join("cache").join("p").join("n").join("a.parquet"), 100, 0);
        touch(&ws.join("runs").join("p.json"), 10, 0);
        touch(&ws.join("runs").join("receipts").join("r1.json"), 20, 0);

        let s = survey(ws);
        let by = |n: &str| s.iter().find(|c| c.category == n).unwrap().clone();
        assert_eq!(by("cache").bytes, 100);
        assert_eq!(by("receipts").bytes, 20);
        assert_eq!(
            by("runs").bytes,
            10,
            "receipts live under runs/ and are reported separately, not twice"
        );
    }

    /// AC2, and the reason this module exists in one piece rather than as four
    /// ad-hoc deletions: `.duckle` holds the workspace key, watermarks and
    /// resume positions. Losing a watermark does not lose history, it silently
    /// re-ingests or skips data.
    #[test]
    fn nothing_under_dot_duckle_can_ever_be_planned_or_applied() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();
        touch(&ws.join(".duckle").join("keys").join("workspace.key"), 32, 900);
        touch(&ws.join(".duckle").join("state").join("watermark.json"), 32, 900);

        let p = plan(ws, &Policy { cache_days: Some(0), logs_days: Some(0), receipts_keep: Some(0) });
        assert!(p.is_empty(), "a retention policy must not reach state: {p:?}");

        // Even asked directly.
        let forced = vec![Removal {
            path: ws.join(".duckle").join("keys").join("workspace.key").display().to_string(),
            category: "cache".into(),
            bytes: 32,
            reason: "forced".into(),
        }];
        let (n, _) = apply(ws, &forced);
        assert_eq!(n, 0, "apply must re-check, not trust its input");
        assert!(ws.join(".duckle").join("keys").join("workspace.key").exists());
    }

    /// AC1: the dry run and the prune are the same list, because they are the
    /// same function.
    #[test]
    fn what_a_dry_run_lists_is_exactly_what_a_prune_removes() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();
        touch(&ws.join("cache").join("p").join("n").join("old.parquet"), 50, 90);
        touch(&ws.join("cache").join("p").join("n").join("new.parquet"), 50, 1);

        let policy = Policy { cache_days: Some(30), ..Default::default() };
        let listed = plan(ws, &policy);
        assert_eq!(listed.len(), 1, "only the old one: {listed:?}");
        assert!(listed[0].path.ends_with("old.parquet"));

        let (n, bytes) = apply(ws, &listed);
        assert_eq!((n, bytes), (1, 50));
        assert!(!ws.join("cache").join("p").join("n").join("old.parquet").exists());
        assert!(
            ws.join("cache").join("p").join("n").join("new.parquet").exists(),
            "a recent entry must survive"
        );
    }

    /// The audit log is the record of the prune's own deletions. A retention
    /// policy that deleted it would erase the evidence it is required to leave.
    #[test]
    fn the_audit_log_is_never_pruned_by_age() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();
        touch(&ws.join("logs").join("audit.ndjson"), 10, 900);
        touch(&ws.join("logs").join("nightly").join("runtime.log"), 10, 900);

        let p = plan(ws, &Policy { logs_days: Some(30), ..Default::default() });
        assert_eq!(p.len(), 1, "{p:?}");
        assert!(p[0].path.ends_with("runtime.log"), "got {}", p[0].path);
    }

    #[test]
    fn receipts_keep_the_newest_and_drop_the_rest() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();
        for (i, age) in [("a", 5u64), ("b", 3), ("c", 1)] {
            touch(&ws.join("runs").join("receipts").join(format!("{i}.json")), 10, age);
        }
        let p = plan(ws, &Policy { receipts_keep: Some(2), ..Default::default() });
        assert_eq!(p.len(), 1, "{p:?}");
        assert!(p[0].path.ends_with("a.json"), "the oldest goes: {}", p[0].path);
    }

    /// An empty policy removes nothing. Retention is opt-in per category, so a
    /// bare `prune` cannot delete anything by surprise.
    #[test]
    fn an_empty_policy_plans_nothing() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();
        touch(&ws.join("cache").join("p").join("n").join("old.parquet"), 50, 900);
        assert!(plan(ws, &Policy::default()).is_empty());
    }
}
